### PR TITLE
Issue 11

### PR DESCRIPTION
**Pull request by nicolabertazzo**
Hi @oscarlvp  and @CaelInria ,

I refactor the project in a maven multi-module project composed of:

- pitmp-maven-plugin: pitmp maven mojo
- pitmp-maven-verification: porting of integration tests from sh to a java project. For now the test execute pitmp:run and pitmp:descartes in 4 example projects.

If you agree with this new structure I'll add the verification of mutation output (xml) in the java tests.

### CODE REVIEW

**Review by oscarlvp — CHANGES_REQUESTED** [review]
@nicolabertazzo the structure seems OK.
Since I don't have `dhell` and `dnoo` the test cases fail on my side but it is only reported that the process exited with a non-zero code. I propose to:
 - Check that these projects are in place and provide a clearer error message before executing any test in `pitmp-maven-verification`. 
 - Add `dhell`, `dnoo` and `dnoo5` as [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to the git repository, so they can be easily fetched.

**Comment by nicolabertazzo** [comment]
Hi @oscarlvp ,
the projects dhell, dnoo and dnoo5 are on https://github.com/STAMP-project/pitmp-maven-plugin/tree/issue_11/pitmp-maven-verification/src/test/resources folder (issue issue_11 branch). Can you give me more details about tests that are failing?

**Comment by oscarlvp** [comment]
My bad. I was executing `mvn verify` and the verification was failing because Maven could not find `pitmp`. With `mvn install` everything works.

**Review by oscarlvp — APPROVED** [review]

**Comment by nicolabertazzo** [comment]
Hi @CaelInria ,
I'm waiting for your approval to merge the pull request.

**Pull request merged**
